/**
 * nizk_crs.c - Common Reference String Implementation
 *
 * L1: The CRS is a shared public string enabling NIZK proofs.
 * Generated by trusted party or MPC ceremony before any proofs.
 *
 * Modes:
 *   - Soundness: h random (unknown DL), ensures soundness
 *   - ZK mode: h = g^tau (tau known), enables simulation
 *
 * Ref: Blum, Feldman, Micali STOC 1988
 *
 * Course: MIT 6.875, Stanford CS355, Princeton COS 551
 */

#include "nizk_crs.h"
#include "nizk_group.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

/* =========================================================================
 * L3: Hash-to-Group - Deriving Group Elements from Seeds
 * ========================================================================= */

/**
 * hash_to_group_element - Map arbitrary bytes to a group element.
 *
 * L3 Knowledge Point: Hash-to-Group (Exponentiation Method)
 *
 * Maps byte strings to uniformly distributed group elements via:
 *   1. Hash seed using DJB2 + Feistel-like expansion -> 256 bits
 *   2. Reduce modulo q to get scalar s
 *   3. Return g^s as group element
 *
 * The exponentiation method: g^s is uniform in G when s is uniform
 * in Z_q (preimage resistance of DL prevents distinguishing from random).
 *
 * For elliptic curves, RFC 9380 defines proper hash-to-curve.
 * For multiplicative groups, hash-to-scalar-then-exponentiate suffices.
 *
 * Course: Stanford CS355 Hash-to-Curve, MIT 6.875 Random Oracle Instantiation
 */
static void hash_to_group_element(nizk_group_elem_t *result,
                                   const uint8_t *seed, size_t seed_len,
                                   const nizk_group_params_t *params) {
    /* DJB2 hash (Daniel J. Bernstein) */
    uint64_t h = 5381;
    for (size_t i = 0; i < seed_len; i++) {
        h = ((h << 5) + h) + seed[i];
    }

    /* Feistel-like entropy expansion: 64 bits -> 256 bits (4 limbs of 64 bits).
     * Each round XOR uses a distinct constant for domain separation. */
    uint64_t extended[4];
    extended[0] = h;
    extended[1] = h ^ 0x5C3A7B1F9E2D4086ULL;
    extended[2] = h ^ 0xA1B2C3D4E5F60718ULL;
    extended[3] = h ^ 0x1F2E3D4C5B6A7988ULL;

    /* Build scalar from expanded entropy */
    nizk_scalar_t s;
    nizk_bigint_zero(&s.val);
    for (int i = 0; i < 4 && i < NIZK_BIGINT_LIMBS; i++) {
        s.val.limbs[i] = extended[i];
    }

    /* Reduce modulo q via trial subtraction.
     * Since value < 2^256 and q ~ 2^256, at most 2 subtractions needed. */
    nizk_bigint_t tmp;
    nizk_bigint_copy(&tmp, &s.val);
    while (nizk_bigint_cmp(&tmp, &params->q) >= 0) {
        uint64_t borrow = 0;
        for (int j = 0; j < NIZK_BIGINT_LIMBS; j++) {
            uint64_t diff = tmp.limbs[j] - params->q.limbs[j] - borrow;
            borrow = (tmp.limbs[j] < params->q.limbs[j] + borrow) ? 1 : 0;
            tmp.limbs[j] = diff;
        }
        if (borrow) break;
    }
    nizk_bigint_copy(&s.val, &tmp);

    /* result = g^s mod p */
    nizk_group_elem_t gen;
    nizk_bigint_copy(&gen.elem, &params->g);
    nizk_group_exp(result, &gen, &s, params);
}

/**
 * hash_to_group_element_ds - Domain-separated hash-to-group.
 *
 * L3 Knowledge Point: Domain Separation
 *
 * Appends a unique domain separation byte to the seed before hashing.
 * Standard: H(domain_tag || message) where domain_tag is unique per context.
 * This ensures h1 and h2 are independent even when derived from the same seed.
 *
 * Without domain separation, h1 = h2 = hash-to-group(seed), which would
 * break the binding property of Pedersen commitments (since h1 = h2).
 */
static void hash_to_group_element_ds(nizk_group_elem_t *result,
                                      const uint8_t *seed, size_t seed_len,
                                      uint8_t domain_sep,
                                      const nizk_group_params_t *params) {
    uint8_t *sep_seed = (uint8_t*)malloc(seed_len + 2);
    if (!sep_seed) return;
    memcpy(sep_seed, seed, seed_len);
    sep_seed[seed_len] = domain_sep;
    sep_seed[seed_len + 1] = 0x00;
    hash_to_group_element(result, sep_seed, seed_len + 2, params);
    free(sep_seed);
}

/* =========================================================================
 * L2: CRS Setup - Soundness Mode (Unknown Discrete Log)
 * ========================================================================= */

/**
 * nizk_crs_setup_soundness - Generate CRS with unknown DL for h.
 *
 * L2 Knowledge Point: Soundness CRS
 *
 * No party knows log_g(h). This ensures soundness: a cheating prover
 * cannot forge proofs because forging requires computing log_g(h),
 * which is the DLOG problem.
 *
 * The CRS Tension:
 *   Soundness mode: h = random, DL unknown -> no forgeries
 *   ZK mode: h = g^tau, DL known -> simulator can fake proofs
 *   You CANNOT have both with a SINGLE CRS in the basic model.
 *
 * Solutions for full NIZK:
 *   1. Separate CRS for soundness and ZK proofs (Groth-Ostrovsky-Sahai)
 *   2. Bilinear groups where different structures provide each property
 *   3. Multi-string model with majority-honest CRS generation
 *
 * Algorithm:
 *   1. h = hash-to-group(seed)        -- unknown DL
 *   2. h1 = hash-to-group(seed||0x01) -- Pedersen base 1
 *   3. h2 = hash-to-group(seed||0x02) -- Pedersen base 2
 *   4. has_trapdoor = 0
 *
 * Theorem: Under DLOG assumption, no PPT adversary can produce
 * a valid proof for a false statement.
 *
 * Course: Princeton COS 551, MIT 6.875, Stanford CS355
 */
void nizk_crs_setup_soundness(nizk_crs_t *crs,
                               const nizk_group_params_t *params,
                               const uint8_t *seed, size_t seed_len) {
    memset(crs, 0, sizeof(*crs));
    crs->type = NIZK_CRS_SCHNORR_PROTOCOL;
    crs->has_trapdoor = 0;
    nizk_scalar_zero(&crs->trapdoor);

    /* h: random element with unknown discrete log */
    hash_to_group_element(&crs->h, seed, seed_len, params);

    /* h1, h2: Pedersen bases with unknown DL relationship */
    hash_to_group_element_ds(&crs->h1, seed, seed_len, 0x01, params);
    hash_to_group_element_ds(&crs->h2, seed, seed_len, 0x02, params);
}

/* =========================================================================
 * L2: CRS Setup - ZK Mode (with Simulation Trapdoor)
 * ========================================================================= */

/**
 * nizk_crs_setup_zk - Generate CRS with known trapdoor for simulation.
 *
 * L2 Knowledge Point: ZK CRS with Simulation Trapdoor
 *
 * The trapdoor tau (h = g^tau) enables simulation without witness:
 *   1. Pick random s, c <- Z_q
 *   2. Compute t = g^s * h^{-c}
 *   3. Program RO: H(stmt || t) = c
 *   4. Output (t, s) as simulated proof
 *
 * The simulated distribution is IDENTICAL to real when tau is uniform:
 *   Real: v uniform, t=g^v, c=H(stmt||t), s=v+c*w
 *   Sim:  s uniform, c uniform, t=g^s*h^{-c}
 *   Both: s uniform in Z_q, c uniform, t determined by (s,c).
 *
 * Theorem (Perfect ZK in ROM): Real proofs ≈ Simulated proofs.
 *
 * Algorithm:
 *   1. If tau provided, use it; else pick random tau <- Z_q
 *   2. h = g^tau
 *   3. Derive h1, h2 from tau (simulator knows their DLs too)
 *   4. has_trapdoor = 1
 *
 * Course: Stanford CS355 Simulation, MIT 6.875 NIZK Security Proofs
 */
void nizk_crs_setup_zk(nizk_crs_t *crs,
                        const nizk_group_params_t *params,
                        const nizk_scalar_t *tau) {
    memset(crs, 0, sizeof(*crs));
    crs->type = NIZK_CRS_SCHNORR_PROTOCOL;
    crs->has_trapdoor = 1;

    if (tau != NULL) {
        nizk_scalar_copy(&crs->trapdoor, tau);
    } else {
        nizk_scalar_rand(&crs->trapdoor, params);
    }

    /* h = g^tau */
    nizk_group_elem_t gen;
    nizk_bigint_copy(&gen.elem, &params->g);
    nizk_group_exp(&crs->h, &gen, &crs->trapdoor, params);

    /* Derive h1, h2 from tau with domain separation.
     * The simulator knows log_g(h1) and log_g(h2), enabling
     * simulation of commitment-opening proofs. */
    nizk_scalar_t tau_h1, tau_h2, ds;
    nizk_scalar_set_u64(&ds, 0x48310001);
    nizk_scalar_add(&tau_h1, &crs->trapdoor, &ds, params);
    nizk_scalar_set_u64(&ds, 0x48320001);
    nizk_scalar_add(&tau_h2, &crs->trapdoor, &ds, params);

    nizk_group_exp(&crs->h1, &gen, &tau_h1, params);
    nizk_group_exp(&crs->h2, &gen, &tau_h2, params);
}

/* =========================================================================
 * L2: CRS Setup - Pedersen Commitment Mode
 * ========================================================================= */

/**
 * nizk_crs_setup_pedersen - Generate CRS for Pedersen commitments.
 *
 * L2 Knowledge Point: Pedersen CRS Setup
 *
 * For binding, NO ONE may know x where h2 = h1^x (the DL relationship).
 * If x is known: C = g^m * h1^r can be opened to (m', r') with
 * r' = r + (m-m')/x mod q, breaking binding.
 *
 * Using nothing-up-my-sleeve hash-to-group ensures unknown DL relationship
 * under the random oracle assumption.
 *
 * Ref: Pedersen, T.P. CRYPTO 1991
 * Course: Berkeley CS278, Cambridge Part III
 */
void nizk_crs_setup_pedersen(nizk_crs_t *crs,
                              const nizk_group_params_t *params,
                              const uint8_t *seed, size_t seed_len) {
    memset(crs, 0, sizeof(*crs));
    crs->type = NIZK_CRS_CHAUM_PEDERSEN;
    crs->has_trapdoor = 0;
    nizk_scalar_zero(&crs->trapdoor);

    hash_to_group_element(&crs->h, seed, seed_len, params);
    hash_to_group_element_ds(&crs->h1, seed, seed_len, 0x01, params);
    hash_to_group_element_ds(&crs->h2, seed, seed_len, 0x02, params);
}

/* =========================================================================
 * L2: CRS Validation
 * ========================================================================= */

/**
 * nizk_crs_validate - Verify CRS is well-formed and secure to use.
 *
 * L2 Knowledge Point: CRS Validation / Subversion Resistance
 *
 * Before using a CRS, verify:
 *   1. All group elements are valid (subgroup membership)
 *   2. No element is identity (would break security)
 *   3. If has_trapdoor, h = g^trapdoor
 *
 * Without validation, a malicious CRS could set h=1 (all proofs verify),
 * or h = g^known (prover who knows DL of h can forge).
 *
 * Subversion-resistant NIZK (Bellare et al., ASIACRYPT 2016) achieves
 * security even with malicious CRS via additional checks.
 *
 * Course: MIT 6.875, ETH 263-4650
 */
int nizk_crs_validate(const nizk_crs_t *crs,
                      const nizk_group_params_t *params) {
    if (crs->type > NIZK_CRS_GENERIC) return 0;

    /* Validate h */
    if (!nizk_group_elem_is_valid(&crs->h, params)) return 0;
    {
        nizk_bigint_t one;
        nizk_bigint_one(&one);
        if (nizk_bigint_cmp(&crs->h.elem, &one) == 0) return 0;
    }

    /* Validate h1, h2 */
    if (!nizk_group_elem_is_valid(&crs->h1, params)) return 0;
    if (!nizk_group_elem_is_valid(&crs->h2, params)) return 0;
    {
        nizk_bigint_t one;
        nizk_bigint_one(&one);
        if (nizk_bigint_cmp(&crs->h1.elem, &one) == 0) return 0;
        if (nizk_bigint_cmp(&crs->h2.elem, &one) == 0) return 0;
    }

    /* Verify trapdoor if claimed */
    if (crs->has_trapdoor) {
        if (!nizk_crs_verify_trapdoor(crs, params)) return 0;
    }

    return 1;
}

/**
 * nizk_crs_verify_trapdoor - Verify that claimed trapdoor matches h.
 *
 * L4 Theorem: h = g^tau iff tau = log_g(h) mod q.
 */
int nizk_crs_verify_trapdoor(const nizk_crs_t *crs,
                              const nizk_group_params_t *params) {
    if (!crs->has_trapdoor) return 0;

    nizk_group_elem_t gen, computed;
    nizk_bigint_copy(&gen.elem, &params->g);
    nizk_group_exp(&computed, &gen, &crs->trapdoor, params);

    return nizk_group_elem_eq(&computed, &crs->h);
}

/* =========================================================================
 * L1: CRS Utility Functions
 * ========================================================================= */

/**
 * nizk_crs_copy - Deep copy a CRS structure.
 * Prevents unintended aliasing of sensitive trapdoor data.
 */
void nizk_crs_copy(nizk_crs_t *dst, const nizk_crs_t *src) {
    dst->type = src->type;
    nizk_group_elem_copy(&dst->h, &src->h);
    nizk_group_elem_copy(&dst->h1, &src->h1);
    nizk_group_elem_copy(&dst->h2, &src->h2);
    nizk_scalar_copy(&dst->trapdoor, &src->trapdoor);
    dst->has_trapdoor = src->has_trapdoor;
}

/**
 * nizk_crs_clear - Zeroize and clear CRS structure.
 *
 * L1 Knowledge Point: Secure Deletion/Zeroization
 * Cryptographic secrets (trapdoor) must be zeroized before deallocation
 * to prevent memory disclosure (cold boot, swap files, core dumps).
 * 'volatile' prevents compiler optimization of zeroization.
 */
void nizk_crs_clear(nizk_crs_t *crs) {
    volatile uint64_t *t = (volatile uint64_t*)&crs->trapdoor;
    for (int i = 0; i < NIZK_BIGINT_LIMBS; i++) {
        t[i] = 0;
    }
    crs->has_trapdoor = 0;
    memset(crs, 0, sizeof(*crs));
}

/**
 * nizk_crs_print - Print CRS for debugging.
 * Does NOT print the trapdoor (security).
 */
void nizk_crs_print(const nizk_crs_t *crs,
                     const nizk_group_params_t *params) {
    (void)params;
    printf("=== Common Reference String ===\n");
    printf("  Type:           %d\n", crs->type);
    printf("  Trapdoor known: %s\n", crs->has_trapdoor ? "yes" : "no");
    printf("  h  (limb[0]):   %016llx\n",
           (unsigned long long)crs->h.elem.limbs[0]);
    printf("  h1 (limb[0]):   %016llx\n",
           (unsigned long long)crs->h1.elem.limbs[0]);
    printf("  h2 (limb[0]):   %016llx\n",
           (unsigned long long)crs->h2.elem.limbs[0]);
}
