/**
 * nizk_crs.h ！ Common Reference String (CRS) Model for NIZK Proofs
 *
 * L1 Definition: A Common Reference String (CRS) is a public string
 * generated by a trusted party (or multi-party computation) that is
 * available to both the prover and verifier before any proof is made.
 *
 * The CRS model is one of the main approaches to achieving non-interactive
 * zero-knowledge proofs, alongside the Random Oracle Model (Fiat-Shamir).
 *
 * In the CRS model:
 *   - Setup(1^lambda) -> crs: Generate CRS (possibly with trapdoor)
 *   - Prove(crs, x, w) -> pi: Generate NIZK proof using CRS
 *   - Verify(crs, x, pi) -> 0/1: Verify NIZK proof using CRS
 *
 * Security properties:
 *   - Completeness: Honest prover with valid witness always convinces verifier
 *   - Soundness: No PPT adversary can prove false statement
 *   - Zero-Knowledge: Proof reveals nothing beyond validity of statement
 *
 * Reference: Blum, Feldman, Micali. "Non-Interactive Zero-Knowledge and
 *            Its Applications." STOC 1988.
 *
 * Course Mapping:
 *   MIT 6.875: NIZK, CRS model
 *   Stanford CS355: Common reference string
 *   Princeton COS 551: NIZK proof systems
 */

#ifndef NIZK_CRS_H
#define NIZK_CRS_H

#include "nizk_group.h"
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---------------------------------------------------------------------------
 * L1: CRS Type Definition
 * ------------------------------------------------------------------------- */

/**
 * nizk_crs_type ！ The type of CRS, determining what proofs it supports.
 */
typedef enum {
    NIZK_CRS_SCHNORR_PROTOCOL = 0,   /* Schnorr DLOG knowledge proof */
    NIZK_CRS_CHAUM_PEDERSEN   = 1,   /* Chaum-Pedersen DLOG equality */
    NIZK_CRS_REPRESENTATION   = 2,   /* Proof of representation */
    NIZK_CRS_OR_PROOF         = 3,   /* OR-composition of sigma protocols */
    NIZK_CRS_GENERIC          = 4,   /* Generic CRS for multiple protocols */
} nizk_crs_type_t;

/**
 * nizk_crs ！ The Common Reference String structure.
 *
 * For the CRS, we include:
 *   - type: What kind of proof system this CRS supports
 *   - g: Generator of group G (must be the same as in group_params)
 *   - h: A random group element whose discrete log relative to g is unknown
 *        (this is the "trapdoor" ！ if someone knows log_g(h), they can
 *         simulate proofs without knowing witnesses)
 *
 * In the real CRS model:
 *   - Soundness CRS: h is a random element (log_g(h) unknown)
 *   - ZK CRS: h = g^tau where tau is the simulation trapdoor
 *
 * For Pedersen commitments within NIZK:
 *   - crs_h1, crs_h2: Two random generators for commitment scheme
 *   - These must have unknown discrete log relationship for binding
 */
typedef struct {
    nizk_crs_type_t   type;
    nizk_group_elem_t h;         /* Secondary generator (trapdoor base) */
    nizk_group_elem_t h1;        /* First Pedersen base */
    nizk_group_elem_t h2;        /* Second Pedersen base */
    nizk_scalar_t     trapdoor;  /* Simulation trapdoor (only in ZK mode) */
    int               has_trapdoor; /* 1 if trapdoor is known, 0 otherwise */
} nizk_crs_t;

/* ---------------------------------------------------------------------------
 * L2: CRS Generation Algorithms
 * ------------------------------------------------------------------------- */

/**
 * nizk_crs_setup_soundness ！ Generate a CRS for the soundness setting.
 *
 * Generates h as a random group element with UNKNOWN discrete logarithm.
 * This ensures soundness: even an unbounded prover cannot prove false
 * statements without knowing the witness.
 *
 * Algorithm:
 *   1. Pick random r <- Z_q
 *   2. Set h = g^r (but discard r ！ we don't need the trapdoor)
 *   Actually, for soundness we want NO ONE to know log_g(h).
 *   In practice, this uses a hash-to-group function (hash and pray).
 *
 * In this mini-implementation, we generate h by hashing a public seed
 * to a group element, ensuring no party knows the discrete log.
 *
 * Parameters:
 *   crs    ！ output CRS structure
 *   params ！ group parameters (G, g, p, q)
 *   seed   ！ public random seed string for deterministic derivation
 *   seed_len ！ length of seed
 *
 * Theorem (Soundness): If the DLOG problem is hard in G, then the
 * Schnorr NIZK protocol with this CRS is sound.
 */
void nizk_crs_setup_soundness(nizk_crs_t *crs,
                               const nizk_group_params_t *params,
                               const uint8_t *seed, size_t seed_len);

/**
 * nizk_crs_setup_zk ！ Generate a CRS with known trapdoor for simulation.
 *
 * Generates h = g^tau where tau is known. The trapdoor tau allows
 * simulation of proofs without witnesses, establishing the ZK property.
 *
 * This is used for:
 *   - Security proofs: Simulator can generate indistinguishable proofs
 *   - Testing: Easy to create valid-looking proofs for test vectors
 *
 * Parameters:
 *   crs    ！ output CRS structure (with has_trapdoor = 1)
 *   params ！ group parameters
 *   tau    ！ trapdoor scalar (log_g(h)); if NULL, random trapdoor is used
 *
 * Theorem (Zero-Knowledge): If tau is chosen uniformly random, then
 * real proofs and simulated proofs are perfectly indistinguishable.
 */
void nizk_crs_setup_zk(nizk_crs_t *crs,
                        const nizk_group_params_t *params,
                        const nizk_scalar_t *tau);

/**
 * nizk_crs_setup_pedersen ！ Generate CRS with Pedersen commitment bases.
 *
 * Sets up h1, h2 as random group generators with unknown discrete log
 * relationship (for binding of Pedersen commitments).
 *
 * The bases are derived deterministically from a seed using
 * hash-to-group, ensuring no party knows log_{h1}(h2).
 */
void nizk_crs_setup_pedersen(nizk_crs_t *crs,
                              const nizk_group_params_t *params,
                              const uint8_t *seed, size_t seed_len);

/* ---------------------------------------------------------------------------
 * L2: CRS Validation
 * ------------------------------------------------------------------------- */

/**
 * nizk_crs_validate ！ Verify that a CRS is well-formed.
 *
 * Checks:
 *   1. CRS type is valid
 *   2. All group elements are valid (members of G)
 *   3. If has_trapdoor, verify h = g^{trapdoor}
 *   4. h1, h2 are not identity and are valid group elements
 *
 * Returns 1 if valid, 0 otherwise.
 */
int  nizk_crs_validate(const nizk_crs_t *crs,
                        const nizk_group_params_t *params);

/**
 * nizk_crs_verify_trapdoor ！ Verify that the trapdoor matches h = g^tau.
 *
 * Used to check that a prover claiming to know the trapdoor
 * actually knows it.
 */
int  nizk_crs_verify_trapdoor(const nizk_crs_t *crs,
                               const nizk_group_params_t *params);

/* ---------------------------------------------------------------------------
 * L1: Core CRS Operations
 * ------------------------------------------------------------------------- */

/** Copy a CRS structure. */
void nizk_crs_copy(nizk_crs_t *dst, const nizk_crs_t *src);

/** Clear/free a CRS structure (zeroize trapdoor). */
void nizk_crs_clear(nizk_crs_t *crs);

/** Print CRS information for debugging. */
void nizk_crs_print(const nizk_crs_t *crs,
                     const nizk_group_params_t *params);

#ifdef __cplusplus
}
#endif

#endif /* NIZK_CRS_H */
