/*
 * simulator.c -- Zero-Knowledge Simulator for GMW Protocol
 *
 * Implements the ZK simulator for the GMW 3-COLORING protocol.
 * The simulator demonstrates that the verifier learns nothing beyond
 * the validity of the statement (graph 3-colorability).
 *
 * L1: Zero-Knowledge definition via simulation paradigm
 * L2: HVZK (Honest-Verifier ZK) vs Malicious-Verifier ZK
 * L3: Simulator strategy: pre-select edge, assign colors, commit
 * L4: GMW protocol is computational ZK (under hiding of commitments)
 * L5: Distinguisher test comparing real vs simulated transcripts
 *
 * Simulator Strategy (HVZK for GMW 3-COLORING):
 *   1. Pick a random edge e = (u,v) in E
 *   2. Pick random distinct colors c_u != c_v in {0,1,2}
 *   3. For vertices u, v: commit to c_u, c_v with proper nonces
 *   4. For all other vertices w: commit to a random color
 *   5. Challenge edge = e, revealed colors = (c_u, c_v)
 *
 * Why this works (computational ZK):
 *   - Real protocol: P commits to permuted 3-coloring, V sees 2 colors
 *   - Simulator: commits to random colors, V sees 2 random distinct colors
 *   - Both produce the same distribution of (commitments, edge, 2 colors)
 *   - Indistinguishable because commitments are hiding (computationally)
 *
 * Reference:
 *   Goldreich, Micali, Wigderson (1986/1991)
 *   Goldreich (2004) FOC I, sec 4.4.2-4.4.3
 *   Goldreich, Oren (1994) "Definitions and Properties of ZK Proof Systems"
 * Courses: MIT 6.876, Stanford CS255
 */
#include "simulator.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>

/* ================================================================
 * Simulator Core
 * ================================================================ */

/*
 * Generate a single simulated GMW transcript.
 *
 * The simulator works WITHOUT knowing a valid 3-coloring of the graph.
 * This is the defining property of zero-knowledge: anything the verifier
 * sees could have been generated by the simulator alone.
 *
 * Strategy:
 *   1. Randomly select an edge e = (u,v) from the graph
 *   2. Pick two random DISTINCT colors c_u, c_v
 *   3. For vertices u, v: proper commitments to c_u, c_v with fresh nonces
 *   4. For all other vertices: commit to COLOR_RED (dummy)
 *   5. Pack everything into a SimulatedTranscript
 *
 * The transcript looks exactly like a real protocol interaction
 * to any computationally bounded observer (because commitments hide
 * the dummy colors on unopened vertices).
 *
 * Complexity: O(|V|) commitments, O(|E|) edge enumeration
 */
SimulatedTranscript* simulator_generate_transcript(const Graph3Col* graph,
                                                    uint64_t seed) {
    if (!graph || graph->n_edges == 0) return NULL;

    int n = graph->n_vertices;
    SimulatedTranscript* trans = (SimulatedTranscript*)malloc(
        sizeof(SimulatedTranscript));
    if (!trans) return NULL;
    memset(trans, 0, sizeof(SimulatedTranscript));

    trans->n_vertices = n;
    trans->n_edges = graph->n_edges;
    trans->sim_seed = seed;

    srand((unsigned int)seed);

    /* Step 1: Pick random edge */
    int target = rand() % graph->n_edges;
    int count = 0;
    trans->edge_u = -1; trans->edge_v = -1;
    for (int i = 0; i < n && trans->edge_u < 0; i++) {
        for (int j = i + 1; j < n; j++) {
            if (graph3_has_edge(graph, i, j)) {
                if (count == target) {
                    trans->edge_u = i;
                    trans->edge_v = j;
                }
                count++;
            }
        }
    }

    /* Step 2: Pick random distinct colors */
    int cu = rand() % NUM_COLORS;
    int cv = rand() % NUM_COLORS;
    /* Ensure distinct */
    if (cu == cv) { cv = (cv + 1) % NUM_COLORS; }
    trans->color_u = cu;
    trans->color_v = cv;

    /* Step 3-4: Generate commitments for all vertices */
    trans->commitments = (HashDigest*)malloc((size_t)n * sizeof(HashDigest));
    trans->nonces = (CommitNonce*)malloc((size_t)n * sizeof(CommitNonce));
    if (!trans->commitments || !trans->nonces) {
        free(trans->commitments); free(trans->nonces);
        free(trans); return NULL;
    }

    for (int v = 0; v < n; v++) {
        commit_generate_nonce(&trans->nonces[v]);

        int color_to_commit;
        if (v == trans->edge_u) {
            color_to_commit = cu;
        } else if (v == trans->edge_v) {
            color_to_commit = cv;
        } else {
            /* Dummy color for unopened vertices */
            color_to_commit = COLOR_RED;
        }

        trans->commitments[v] = commit_color(color_to_commit, &trans->nonces[v]);
    }

    /* Copy nonces for the two opened vertices */
    memcpy(&trans->nonce_u, &trans->nonces[trans->edge_u], sizeof(CommitNonce));
    memcpy(&trans->nonce_v, &trans->nonces[trans->edge_v], sizeof(CommitNonce));

    return trans;
}

/*
 * Generate multiple simulated transcripts.
 * Returns array of SimulatedTranscript* pointers.
 * Different seeds produce different (independent) transcripts.
 */
SimulatedTranscript** simulator_generate_transcripts(const Graph3Col* graph,
                                                      int n_transcripts,
                                                      uint64_t base_seed) {
    if (!graph || n_transcripts <= 0) return NULL;

    SimulatedTranscript** transcripts = (SimulatedTranscript**)malloc(
        (size_t)n_transcripts * sizeof(SimulatedTranscript*));
    if (!transcripts) return NULL;

    for (int i = 0; i < n_transcripts; i++) {
        transcripts[i] = simulator_generate_transcript(graph, base_seed + (uint64_t)i);
        if (!transcripts[i]) {
            for (int j = 0; j < i; j++)
                simulator_free_transcript(transcripts[j]);
            free(transcripts);
            return NULL;
        }
    }

    return transcripts;
}

/*
 * Free a simulated transcript.
 */
void simulator_free_transcript(SimulatedTranscript* transcript) {
    if (!transcript) return;
    free(transcript->commitments);
    free(transcript->nonces);
    free(transcript);
}

/*
 * Generate a REAL GMW transcript (for comparison with simulated).
 * Uses the actual prover with the given 3-coloring.
 *
 * This creates a full GMWSession and runs all rounds, then
 * extracts the transcript.
 */
GMWTranscript* simulator_generate_real_transcript(const Graph3Col* graph,
                                                   const Coloring3* coloring,
                                                   int n_rounds,
                                                   uint64_t seed) {
    if (!graph || !coloring || n_rounds <= 0) return NULL;

    /* Clone coloring to avoid modifying the original */
    Coloring3* col_clone = coloring3_clone(coloring);
    if (!col_clone) return NULL;
    col_clone->valid = coloring3_verify(graph, coloring);

    /* Create prover session and run protocol */
    GMWSession* session = gmw_session_create(
        (Graph3Col*)graph, col_clone, 1, n_rounds);
    if (!session) { coloring3_free(col_clone); return NULL; }

    /* For real transcript generation, we need a combined session.
     * We'll simulate both prover and verifier in one process. */
    /* Since gmw_execute_round expects the session to know its role,
     * let's generate the transcript directly. */

    GMWTranscript* trans = (GMWTranscript*)malloc(sizeof(GMWTranscript));
    if (!trans) { gmw_session_free(session); coloring3_free(col_clone); return NULL; }

    trans->n_vertices = graph->n_vertices;
    trans->n_edges = graph->n_edges;
    trans->n_rounds = n_rounds;
    trans->rounds = (GMWRound**)malloc((size_t)n_rounds * sizeof(GMWRound*));
    trans->verifier_accept = 1;

    srand((unsigned int)seed);

    for (int r = 0; r < n_rounds; r++) {
        GMWRound* round = gmw_round_create(r, graph->n_vertices);
        if (!round) { trans->verifier_accept = 0; break; }

        /* Prover commits */
        int result = gmw_prover_commit(session, round);
        if (result != 1) { trans->verifier_accept = 0; gmw_round_free(round, graph->n_vertices); break; }

        /* Verifier challenges: pick random edge */
        int target = rand() % graph->n_edges;
        int cnt = 0;
        for (int i = 0; i < graph->n_vertices; i++) {
            for (int j = i + 1; j < graph->n_vertices; j++) {
                if (graph3_has_edge(graph, i, j)) {
                    if (cnt == target) {
                        round->challenge_u = i;
                        round->challenge_v = j;
                    }
                    cnt++;
                }
            }
        }

        /* Prover reveals */
        result = gmw_prover_reveal(session, round,
            round->challenge_u, round->challenge_v);
        if (result != 1) { trans->verifier_accept = 0; gmw_round_free(round, graph->n_vertices); break; }

        /* Verifier verifies: we simulate by checking ourselves */
        int u = round->challenge_u, v = round->challenge_v;
        int cu = round->revealed_color_u, cv = round->revealed_color_v;
        if (cu == cv || cu < 0 || cu >= NUM_COLORS || cv < 0 || cv >= NUM_COLORS) {
            round->verifier_accept = 0;
        } else if (!commit_verify_color(cu, &round->nonces[u], &round->commitments[u]) ||
                   !commit_verify_color(cv, &round->nonces[v], &round->commitments[v])) {
            round->verifier_accept = 0;
        } else {
            round->verifier_accept = 1;
        }

        if (!round->verifier_accept) { trans->verifier_accept = 0; }

        round->phase = GMW_PHASE_VERIFY;
        trans->rounds[r] = round;
    }

    gmw_session_free(session);
    coloring3_free(col_clone);
    return trans;
}

/* ================================================================
 * ZK Distinguisher
 * ================================================================ */

/*
 * Run a distinguisher test comparing simulated vs real transcripts.
 *
 * This computes the total variation distance between the empirical
 * distributions of observed color pairs in simulated and real transcripts.
 *
 * If ZK holds computationally, TVD should be negligible.
 * For the GMW protocol with perfect hiding commitments, we expect
 * exact statistical indistinguishability in the honest-verifier case.
 *
 * The test collects color pairs (c_u, c_v) observed by the verifier
 * across many transcript samples, then compares the distributions.
 *
 * Complexity: O(n_samples * |V|) commitments
 */
ZKDistinguisherReport* zk_distinguisher_run(const Graph3Col* graph,
                                              const Coloring3* coloring,
                                              int n_samples,
                                              uint64_t seed) {
    if (!graph || !coloring || n_samples <= 0) return NULL;

    ZKDistinguisherReport* report = (ZKDistinguisherReport*)malloc(
        sizeof(ZKDistinguisherReport));
    if (!report) return NULL;
    memset(report, 0, sizeof(ZKDistinguisherReport));
    report->samples_compared = n_samples;

    /* Count color-pair frequencies in simulated transcripts */
    int sim_counts[NUM_COLORS][NUM_COLORS] = {{0}};
    int sim_total = 0;

    for (int i = 0; i < n_samples; i++) {
        SimulatedTranscript* t = simulator_generate_transcript(
            graph, seed + (uint64_t)(i * 2));
        if (!t) continue;
        int cu = t->color_u, cv = t->color_v;
        if (cu >= 0 && cu < NUM_COLORS && cv >= 0 && cv < NUM_COLORS) {
            sim_counts[cu][cv]++;
            sim_total++;
        }
        simulator_free_transcript(t);
    }

    /* Count color-pair frequencies in real transcripts */
    int real_counts[NUM_COLORS][NUM_COLORS] = {{0}};
    int real_total = 0;

    for (int i = 0; i < n_samples; i++) {
        GMWTranscript* t = simulator_generate_real_transcript(
            graph, coloring, 1, seed + (uint64_t)(i * 2 + 1));
        if (!t || t->n_rounds < 1) continue;
        GMWRound* r = t->rounds[0];
        int cu = r->revealed_color_u, cv = r->revealed_color_v;
        if (cu >= 0 && cu < NUM_COLORS && cv >= 0 && cv < NUM_COLORS) {
            real_counts[cu][cv]++;
            real_total++;
        }
        /* Free transcript (rounds are owned by session, careful) */
        if (t->rounds) {
            for (int j = 0; j < t->n_rounds; j++)
                gmw_round_free(t->rounds[j], graph->n_vertices);
            free(t->rounds);
        }
        free(t);
    }

    /* Compute distributions and total variation distance */
    double tvd = 0.0;
    for (int i = 0; i < NUM_COLORS; i++) {
        for (int j = 0; j < NUM_COLORS; j++) {
            if (sim_total > 0)
                report->color_dist_sim[i][j] = (double)sim_counts[i][j] / sim_total;
            if (real_total > 0)
                report->color_dist_real[i][j] = (double)real_counts[i][j] / real_total;
            double diff = report->color_dist_sim[i][j] - report->color_dist_real[i][j];
            if (diff < 0) diff = -diff;
            if (diff > tvd) tvd = diff;
        }
    }
    /* Total variation distance = 1/2 * sum |P(i) - Q(i)| */
    tvd = 0.0;
    for (int i = 0; i < NUM_COLORS; i++) {
        for (int j = 0; j < NUM_COLORS; j++) {
            tvd += fabs(report->color_dist_sim[i][j] - report->color_dist_real[i][j]);
        }
    }
    tvd /= 2.0;
    report->total_variation_distance = tvd;

    return report;
}

void zk_distinguisher_report_free(ZKDistinguisherReport* report) {
    free(report);
}

/*
 * Print distinguisher report.
 */
void zk_distinguisher_report_print(const ZKDistinguisherReport* report) {
    if (!report) return;
    printf("=== ZK Distinguisher Report ===\n");
    printf("Samples compared: %d\n", report->samples_compared);
    printf("Total Variation Distance: %.6f\n", report->total_variation_distance);
    printf("(TVD close to 0 => distributions indistinguishable => ZK holds)\n");
    printf("\nSimulated distribution:\n");
    for (int i = 0; i < NUM_COLORS; i++) {
        for (int j = 0; j < NUM_COLORS; j++) {
            if (i != j) {
                printf("  (%s,%s): %.4f\n", COLOR_STRING(i), COLOR_STRING(j),
                       report->color_dist_sim[i][j]);
            }
        }
    }
    printf("Real distribution:\n");
    for (int i = 0; i < NUM_COLORS; i++) {
        for (int j = 0; j < NUM_COLORS; j++) {
            if (i != j) {
                printf("  (%s,%s): %.4f\n", COLOR_STRING(i), COLOR_STRING(j),
                       report->color_dist_real[i][j]);
            }
        }
    }
}

/* ================================================================
 * Simulator Verification
 * ================================================================ */

/*
 * Verify that a simulated transcript is internally consistent.
 * Checks:
 *   1. The challenge edge (u,v) actually exists in the graph
 *   2. The revealed colors are valid and different
 *   3. The commitments for u and v match the revealed colors + nonces
 *
 * This is a necessary condition for ZK (the simulator must produce
 * transcripts that would be accepted by the honest verifier).
 * It is NOT sufficient for ZK (need indistinguishability proof).
 */
int simulator_verify_consistency(const SimulatedTranscript* transcript,
                                  const Graph3Col* graph) {
    if (!transcript || !graph) return 0;
    if (transcript->n_vertices != graph->n_vertices) return 0;

    int u = transcript->edge_u, v = transcript->edge_v;

    if (!graph3_has_edge(graph, u, v)) return 0;
    if (transcript->color_u == transcript->color_v) return 0;
    if (transcript->color_u < 0 || transcript->color_u >= NUM_COLORS) return 0;
    if (transcript->color_v < 0 || transcript->color_v >= NUM_COLORS) return 0;

    if (!commit_verify_color(transcript->color_u, &transcript->nonce_u,
                              &transcript->commitments[u])) return 0;
    if (!commit_verify_color(transcript->color_v, &transcript->nonce_v,
                              &transcript->commitments[v])) return 0;

    return 1;
}

/*
 * Structural test: compare challenge edge distribution and color difference
 * property between simulated and real transcripts.
 *
 * Returns 1 if structural properties match (ZK plausible), 0 otherwise.
 */
int simulator_structural_test(const Graph3Col* graph,
                               const Coloring3* coloring,
                               int n_trials, uint64_t seed) {
    if (!graph || !coloring || n_trials <= 0) return 0;

    /* Run distinguisher and check TVD */
    ZKDistinguisherReport* report = zk_distinguisher_run(
        graph, coloring, n_trials, seed);
    if (!report) return 0;

    /* If TVD is small (< 0.3 for this demo, rigorous values are much smaller),
     * we consider the structural test passed. */
    int passed = (report->total_variation_distance < 0.30) ? 1 : 0;

    zk_distinguisher_report_free(report);
    return passed;
}

/* ================================================================
 * Simulator for General NP via 3-COLORING Reduction
 * ================================================================ */

/*
 * Generate a simulated transcript for any NP language via the
 * NP-completeness reduction to 3-COLORING.
 *
 * Input:
 *   language_name   - name of the NP language
 *   np_witness      - witness for the NP statement
 *   reduction_to_3col - function mapping witness -> (graph, coloring)
 *   seed            - random seed for simulator
 *
 * This demonstrates the GMW Theorem: EVERY language in NP has a
 * computational zero-knowledge proof system.
 *
 * The proof:
 *   For any L in NP, there exists a reduction R: L <=p 3-COLORING
 *   Given instance x, compute R(x) = graph G
 *   If x in L with witness w, R also produces a 3-coloring of G
 *   Run GMW protocol on G -> ZK proof for L
 *
 * Complexity: O(|V|) commitments + cost of reduction
 */
SimulatedTranscript* simulator_np_language(const char* language_name,
                                            const void* np_witness,
                                            int (*reduction_to_3col)(
                                                const void*, Graph3Col**, Coloring3**),
                                            uint64_t seed) {
    if (!language_name || !reduction_to_3col) return NULL;

    /* Apply reduction: witness -> (graph, coloring) */
    Graph3Col* graph = NULL;
    Coloring3* coloring = NULL;
    int ok = reduction_to_3col(np_witness, &graph, &coloring);
    if (!ok || !graph) return NULL;

    /* Generate simulated transcript on the reduced graph */
    SimulatedTranscript* trans = simulator_generate_transcript(graph, seed);

    /* Clean up reduction artifacts */
    if (coloring) coloring3_free(coloring);
    /* Note: graph is not freed here (caller may need it) */

    return trans;
}
